import { Gig, User, Order, Category } from "@/types";

// ============================================
// CATEGORIES
// ============================================

export const CATEGORIES: Category[] = [
    {
        id: "cat-1",
        name: "Graphics & Design",
        slug: "graphics-design",
        icon: "🎨",
        description: "Logo design, branding, illustrations, and more",
        gigCount: 1250,
        subcategories: [
            { id: "sub-1-1", categoryId: "cat-1", name: "Logo Design", slug: "logo-design", gigCount: 450 },
            { id: "sub-1-2", categoryId: "cat-1", name: "Brand Style Guides", slug: "brand-style-guides", gigCount: 200 },
            { id: "sub-1-3", categoryId: "cat-1", name: "Illustration", slug: "illustration", gigCount: 300 },
            { id: "sub-1-4", categoryId: "cat-1", name: "UI/UX Design", slug: "ui-ux-design", gigCount: 300 },
        ],
    },
    {
        id: "cat-2",
        name: "Programming & Tech",
        slug: "programming-tech",
        icon: "💻",
        description: "Web development, mobile apps, and software solutions",
        gigCount: 2100,
        subcategories: [
            { id: "sub-2-1", categoryId: "cat-2", name: "Website Development", slug: "website-development", gigCount: 800 },
            { id: "sub-2-2", categoryId: "cat-2", name: "Mobile Apps", slug: "mobile-apps", gigCount: 500 },
            { id: "sub-2-3", categoryId: "cat-2", name: "API Development", slug: "api-development", gigCount: 400 },
            { id: "sub-2-4", categoryId: "cat-2", name: "DevOps & Cloud", slug: "devops-cloud", gigCount: 400 },
        ],
    },
    {
        id: "cat-3",
        name: "Digital Marketing",
        slug: "digital-marketing",
        icon: "📱",
        description: "SEO, social media, content marketing, and advertising",
        gigCount: 950,
        subcategories: [
            { id: "sub-3-1", categoryId: "cat-3", name: "SEO", slug: "seo", gigCount: 350 },
            { id: "sub-3-2", categoryId: "cat-3", name: "Social Media Marketing", slug: "social-media-marketing", gigCount: 300 },
            { id: "sub-3-3", categoryId: "cat-3", name: "Content Marketing", slug: "content-marketing", gigCount: 200 },
            { id: "sub-3-4", categoryId: "cat-3", name: "Email Marketing", slug: "email-marketing", gigCount: 100 },
        ],
    },
    {
        id: "cat-4",
        name: "Writing & Translation",
        slug: "writing-translation",
        icon: "✍️",
        description: "Content writing, copywriting, and translation services",
        gigCount: 1500,
        subcategories: [
            { id: "sub-4-1", categoryId: "cat-4", name: "Articles & Blog Posts", slug: "articles-blog-posts", gigCount: 600 },
            { id: "sub-4-2", categoryId: "cat-4", name: "Copywriting", slug: "copywriting", gigCount: 400 },
            { id: "sub-4-3", categoryId: "cat-4", name: "Translation", slug: "translation", gigCount: 300 },
            { id: "sub-4-4", categoryId: "cat-4", name: "Proofreading & Editing", slug: "proofreading-editing", gigCount: 200 },
        ],
    },
    {
        id: "cat-5",
        name: "Video & Animation",
        slug: "video-animation",
        icon: "🎬",
        description: "Video editing, animation, and motion graphics",
        gigCount: 800,
        subcategories: [
            { id: "sub-5-1", categoryId: "cat-5", name: "Video Editing", slug: "video-editing", gigCount: 350 },
            { id: "sub-5-2", categoryId: "cat-5", name: "Animation", slug: "animation", gigCount: 250 },
            { id: "sub-5-3", categoryId: "cat-5", name: "Motion Graphics", slug: "motion-graphics", gigCount: 200 },
        ],
    },
    {
        id: "cat-6",
        name: "Music & Audio",
        slug: "music-audio",
        icon: "🎵",
        description: "Music production, voiceovers, and audio editing",
        gigCount: 600,
        subcategories: [
            { id: "sub-6-1", categoryId: "cat-6", name: "Voiceover", slug: "voiceover", gigCount: 250 },
            { id: "sub-6-2", categoryId: "cat-6", name: "Music Production", slug: "music-production", gigCount: 200 },
            { id: "sub-6-3", categoryId: "cat-6", name: "Audio Editing", slug: "audio-editing", gigCount: 150 },
        ],
    },
    {
        id: "cat-7",
        name: "Business",
        slug: "business",
        icon: "💼",
        description: "Business consulting, virtual assistance, and more",
        gigCount: 700,
        subcategories: [
            { id: "sub-7-1", categoryId: "cat-7", name: "Virtual Assistant", slug: "virtual-assistant", gigCount: 300 },
            { id: "sub-7-2", categoryId: "cat-7", name: "Business Consulting", slug: "business-consulting", gigCount: 200 },
            { id: "sub-7-3", categoryId: "cat-7", name: "Data Entry", slug: "data-entry", gigCount: 200 },
        ],
    },
    {
        id: "cat-8",
        name: "AI Services",
        slug: "ai-services",
        icon: "🤖",
        description: "AI development, chatbots, and machine learning",
        gigCount: 450,
        subcategories: [
            { id: "sub-8-1", categoryId: "cat-8", name: "AI Chatbots", slug: "ai-chatbots", gigCount: 200 },
            { id: "sub-8-2", categoryId: "cat-8", name: "Machine Learning", slug: "machine-learning", gigCount: 150 },
            { id: "sub-8-3", categoryId: "cat-8", name: "AI Content Generation", slug: "ai-content-generation", gigCount: 100 },
        ],
    },
];

// ============================================
// MOCK USERS
// ============================================

export const MOCK_USERS: Record<string, User> = {
    u1: {
        id: "u1",
        email: "ahmed@example.com",
        username: "ahmed_kamal",
        fullName: "Ahmed Kamal",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ahmed",
        role: "SELLER",
        status: "ACTIVE",
        bio: "Professional graphic designer with 5+ years of experience. Specialized in logo design and brand identity.",
        location: "Cairo, Egypt",
        languages: ["English", "Arabic"],
        skills: ["Logo Design", "Branding", "Illustrator", "Photoshop"],
        rating: 4.9,
        totalReviews: 124,
        totalEarnings: 45000,
        totalSpent: 0,
        memberSince: new Date("2023-01-15"),
        lastActive: new Date(),
        isVerified: true,
        isOnline: true,
        socialLinks: {
            website: "https://ahmedkamal.design",
            linkedin: "https://linkedin.com/in/ahmedkamal",
        },
    },
    u2: {
        id: "u2",
        email: "sara@example.com",
        username: "sara_dev",
        fullName: "Sara Designer",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sara",
        role: "SELLER",
        status: "ACTIVE",
        bio: "Full-stack developer specializing in Next.js and React. Building modern web applications.",
        location: "Alexandria, Egypt",
        languages: ["English", "Arabic", "French"],
        skills: ["Next.js", "React", "TypeScript", "Node.js", "Tailwind CSS"],
        rating: 4.8,
        totalReviews: 89,
        totalEarnings: 120000,
        totalSpent: 0,
        memberSince: new Date("2022-03-20"),
        lastActive: new Date(),
        isVerified: true,
        isOnline: false,
        socialLinks: {
            github: "https://github.com/saradev",
            linkedin: "https://linkedin.com/in/saradev",
        },
    },
    buyer1: {
        id: "buyer1",
        email: "john@business.com",
        username: "john_business",
        fullName: "John Business",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=John",
        role: "BUYER",
        status: "ACTIVE",
        bio: "Entrepreneur looking for talented freelancers to help grow my business.",
        location: "London, UK",
        languages: ["English"],
        skills: [],
        rating: 5.0,
        totalReviews: 12,
        totalEarnings: 0,
        totalSpent: 25000,
        memberSince: new Date("2023-05-10"),
        lastActive: new Date(),
        isVerified: true,
        isOnline: true,
    },
};

// ============================================
// MOCK GIGS
// ============================================

export const MOCK_GIGS: Gig[] = [
    {
        id: "g1",
        sellerId: "u1",
        seller: MOCK_USERS.u1,
        title: "I will design a professional logo for your startup",
        slug: "professional-logo-design-startup",
        description:
            "Looking for a clean, modern logo? I specialize in minimalist identity design that works across all platforms. My process includes detailed research and multiple concepts to ensure your brand stands out.",
        category: "Graphics & Design",
        subcategory: "Logo Design",
        tags: ["Logo Design", "Branding", "Minimalist", "Startup"],
        images: [
            "https://picsum.photos/seed/logo1/800/600",
            "https://picsum.photos/seed/logo2/800/600",
            "https://picsum.photos/seed/logo3/800/600",
        ],
        packages: [
            {
                name: "BASIC",
                title: "Basic Logo",
                description: "1 Logo concept, PNG/JPG high quality files",
                price: 50,
                deliveryTime: "3_DAYS",
                revisions: 1,
                features: ["1 Logo Concept", "High Resolution", "PNG & JPG Files", "Logo Transparency"],
            },
            {
                name: "STANDARD",
                title: "Standard Package",
                description: "2 Logo concepts, Source File, Vector File",
                price: 120,
                deliveryTime: "7_DAYS",
                revisions: 3,
                features: ["2 Logo Concepts", "Source File", "Vector File", "Logo Transparency", "3 Revisions"],
            },
            {
                name: "PREMIUM",
                title: "Premium Branding",
                description: "3 Concepts, Stationary, Social Media Kit",
                price: 250,
                deliveryTime: "14_DAYS",
                revisions: 99,
                features: [
                    "3 Logo Concepts",
                    "Stationary Designs",
                    "Social Media Kit",
                    "Source File",
                    "Unlimited Revisions",
                    "Brand Guidelines",
                ],
            },
        ],
        status: "ACTIVE",
        rating: 4.9,
        totalReviews: 84,
        totalOrders: 156,
        totalRevenue: 18720,
        isFeatured: true,
        createdAt: new Date("2023-02-01"),
        updatedAt: new Date("2024-12-01"),
        faqs: [
            {
                question: "What do I need to provide?",
                answer: "Your company name, preferred colors, and any style preferences you have.",
            },
            {
                question: "Do you provide source files?",
                answer: "Yes, source files are included in Standard and Premium packages.",
            },
        ],
        requirements: ["Company name", "Preferred colors", "Industry/niche", "Style preferences"],
    },
    {
        id: "g2",
        sellerId: "u2",
        seller: MOCK_USERS.u2,
        title: "I will create a responsive Next.js web application",
        slug: "nextjs-web-application-development",
        description:
            "Get a blazing fast web app built with the latest technologies including Tailwind CSS and TypeScript. I ensure SEO optimization and mobile-first design for the best user experience.",
        category: "Programming & Tech",
        subcategory: "Website Development",
        tags: ["Next.js", "React", "Web Development", "TypeScript", "Tailwind CSS"],
        images: [
            "https://picsum.photos/seed/code1/800/600",
            "https://picsum.photos/seed/code2/800/600",
            "https://picsum.photos/seed/code3/800/600",
        ],
        packages: [
            {
                name: "BASIC",
                title: "Landing Page",
                description: "Single page responsive website",
                price: 350,
                deliveryTime: "7_DAYS",
                revisions: 2,
                features: ["1 Page", "Responsive Design", "SEO Basics", "Deployment Help"],
            },
            {
                name: "STANDARD",
                title: "Multi-Page App",
                description: "Multi-page app with state management",
                price: 800,
                deliveryTime: "14_DAYS",
                revisions: 5,
                features: ["Up to 5 Pages", "API Integration", "SEO Setup", "Contact Forms", "Analytics"],
            },
            {
                name: "PREMIUM",
                title: "Full Solution",
                description: "Full E-commerce solution with Dashboard",
                price: 2500,
                deliveryTime: "30_DAYS",
                revisions: 10,
                features: [
                    "Full Backend",
                    "Payment Integration",
                    "Admin Panel",
                    "User Authentication",
                    "Database Setup",
                    "Priority Support",
                ],
            },
        ],
        status: "ACTIVE",
        rating: 5.0,
        totalReviews: 42,
        totalOrders: 67,
        totalRevenue: 53600,
        isFeatured: true,
        createdAt: new Date("2023-04-15"),
        updatedAt: new Date("2024-12-10"),
        faqs: [
            {
                question: "What technologies do you use?",
                answer: "Next.js 14+, React, TypeScript, Tailwind CSS, and modern best practices.",
            },
            {
                question: "Do you provide hosting?",
                answer: "I can help deploy to Vercel, Netlify, or your preferred platform.",
            },
        ],
        requirements: ["Project requirements", "Design files or references", "Content and images", "Domain (if available)"],
    },
    {
        id: "g3",
        sellerId: "u1",
        seller: MOCK_USERS.u1,
        title: "I will write SEO optimized blog posts for your niche",
        slug: "seo-optimized-blog-posts",
        description:
            "High quality content that ranks on Google. 100% original and plagiarism-free. I cover topics ranging from technology to lifestyle with thorough research and engaging writing.",
        category: "Writing & Translation",
        subcategory: "Articles & Blog Posts",
        tags: ["SEO Writing", "Copywriting", "Content Marketing", "Blog Posts"],
        images: [
            "https://picsum.photos/seed/writing1/800/600",
            "https://picsum.photos/seed/writing2/800/600",
        ],
        packages: [
            {
                name: "BASIC",
                title: "500 Words",
                description: "500 words article with 1 focus keyword",
                price: 30,
                deliveryTime: "1_DAY",
                revisions: 1,
                features: ["500 Words", "Keyword Research", "1 Focus Keyword", "SEO Optimized"],
            },
            {
                name: "STANDARD",
                title: "1500 Words",
                description: "1500 words article with in-depth research",
                price: 75,
                deliveryTime: "3_DAYS",
                revisions: 2,
                features: ["1500 Words", "Topic Research", "Meta Description", "Internal Linking", "2 Revisions"],
            },
            {
                name: "PREMIUM",
                title: "3000 Words",
                description: "3000 words + Competitor analysis + Internal links",
                price: 150,
                deliveryTime: "7_DAYS",
                revisions: 5,
                features: [
                    "3000 Words",
                    "Full SEO Audit",
                    "Competitor Analysis",
                    "Image Selection",
                    "Meta Tags",
                    "5 Revisions",
                ],
            },
        ],
        status: "ACTIVE",
        rating: 4.7,
        totalReviews: 215,
        totalOrders: 389,
        totalRevenue: 29175,
        isFeatured: false,
        createdAt: new Date("2023-01-20"),
        updatedAt: new Date("2024-11-28"),
    },
    {
        id: "g4",
        sellerId: "u2",
        seller: MOCK_USERS.u2,
        title: "I will develop custom AI Chatbots for your website",
        slug: "custom-ai-chatbot-development",
        description:
            "Integrate GPT-4 or custom LLMs into your business flow to automate customer support and lead generation. Modern AI solutions tailored to your needs.",
        category: "AI Services",
        subcategory: "AI Chatbots",
        tags: ["AI", "Chatbot", "Automation", "GPT-4", "Machine Learning"],
        images: [
            "https://picsum.photos/seed/ai1/800/600",
            "https://picsum.photos/seed/ai2/800/600",
            "https://picsum.photos/seed/ai3/800/600",
        ],
        packages: [
            {
                name: "BASIC",
                title: "Simple Q&A Bot",
                description: "Basic FAQ chatbot",
                price: 500,
                deliveryTime: "7_DAYS",
                revisions: 2,
                features: ["100 FAQs", "Web Integration", "Basic Customization", "Documentation"],
            },
            {
                name: "STANDARD",
                title: "Lead Gen Bot",
                description: "Lead generation bot with CRM sync",
                price: 1200,
                deliveryTime: "14_DAYS",
                revisions: 5,
                features: ["CRM Integration", "Custom Personality", "Lead Capture", "Analytics Dashboard", "Email Notifications"],
            },
            {
                name: "PREMIUM",
                title: "Enterprise Agent",
                description: "Enterprise AI agent with tool use",
                price: 4500,
                deliveryTime: "30_DAYS",
                revisions: 99,
                features: [
                    "Custom Training",
                    "API Tool Use",
                    "Priority Support",
                    "Advanced Analytics",
                    "Multi-language",
                    "Unlimited Updates (30 days)",
                ],
            },
        ],
        status: "ACTIVE",
        rating: 4.8,
        totalReviews: 15,
        totalOrders: 23,
        totalRevenue: 27600,
        isFeatured: true,
        createdAt: new Date("2024-01-10"),
        updatedAt: new Date("2024-12-15"),
    },
];

// ============================================
// MOCK ORDERS
// ============================================

export const MOCK_ORDERS: Order[] = [
    {
        id: "o1",
        gigId: "g1",
        gig: MOCK_GIGS[0],
        buyerId: "buyer1",
        buyer: MOCK_USERS.buyer1,
        sellerId: "u1",
        seller: MOCK_USERS.u1,
        packageType: "STANDARD",
        price: 120,
        serviceFee: 12,
        totalAmount: 132,
        status: "IN_PROGRESS",
        paymentStatus: "COMPLETED",
        deliveryDate: new Date("2024-12-25"),
        requirements: {
            "Company name": "TechStart Inc",
            "Preferred colors": "Blue and Green",
            "Industry/niche": "Technology",
        },
        revisionCount: 0,
        maxRevisions: 3,
        createdAt: new Date("2024-12-18"),
        updatedAt: new Date("2024-12-18"),
    },
    {
        id: "o2",
        gigId: "g2",
        gig: MOCK_GIGS[1],
        buyerId: "buyer1",
        buyer: MOCK_USERS.buyer1,
        sellerId: "u2",
        seller: MOCK_USERS.u2,
        packageType: "BASIC",
        price: 350,
        serviceFee: 35,
        totalAmount: 385,
        status: "COMPLETED",
        paymentStatus: "COMPLETED",
        deliveryDate: new Date("2024-12-05"),
        revisionCount: 1,
        maxRevisions: 2,
        createdAt: new Date("2024-11-28"),
        updatedAt: new Date("2024-12-05"),
        completedAt: new Date("2024-12-05"),
    },
];

// ============================================
// APP CONFIGURATION
// ============================================

export const APP_CONFIG = {
    name: "GigStream",
    description: "Find Perfect Freelance Services",
    url: "https://gigstream.com",
    serviceFeePercentage: 10,
    minWithdrawal: 50,
    supportEmail: "support@gigstream.com",
    socialLinks: {
        twitter: "https://twitter.com/gigstream",
        facebook: "https://facebook.com/gigstream",
        instagram: "https://instagram.com/gigstream",
        linkedin: "https://linkedin.com/company/gigstream",
    },
};

export const DELIVERY_TIME_OPTIONS = [
    { value: "1_DAY", label: "1 Day" },
    { value: "3_DAYS", label: "3 Days" },
    { value: "7_DAYS", label: "7 Days" },
    { value: "14_DAYS", label: "14 Days" },
    { value: "30_DAYS", label: "30 Days" },
];

export const SORT_OPTIONS = [
    { value: "RELEVANCE", label: "Relevance" },
    { value: "RATING", label: "Best Rating" },
    { value: "PRICE_LOW", label: "Price: Low to High" },
    { value: "PRICE_HIGH", label: "Price: High to Low" },
    { value: "NEWEST", label: "Newest First" },
];
